default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 1.0e-5
    learning_rate_schedule: linear
    max_steps: 15.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: true
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

Shooter:
    normalize: false
    beta: 5.0e-3
    batch_size: 2048
    buffer_size: 20480
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256


Shooter2:
    normalize: false
    beta: 5.0e-3
    batch_size: 1024
    buffer_size: 20480
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.8
        curiosity:
            strength: 0.02
            gamma: 0.8
            encoding_size: 512


    
Shooter3:
    normalize: false
    beta: 5.0e-3
    memory_size: 512
    batch_size: 4048
    buffer_size: 20480
    
Shooter4:
    normalize: true
    beta: 5.0e-3
    batch_size: 1024
    buffer_size: 20480
    
Shooter5:
    normalize: false
    beta: 5.0e-2
    batch_size: 1024
    num_epoch: 4
    buffer_size: 20480
    
Shooter6:
    normalize: false
    beta: 5.0e-3
    batch_size: 1024
    buffer_size: 10240