default:
    trainer: ppo
    batch_size: 1024 
    buffer_size: 10240
    hidden_units: 128
    learning_rate_schedule: linear
    max_steps: 5.0e5
    memory_size: 1024
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 2500
    use_recurrent: true
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
            
    lambd: 0.95

    epsilon: 0.2
    learning_rate: 3.0e-4
    beta: 5.0e-3

Shooter1PPO:
    batch_size: 218 
    buffer_size: 10240

Shooter2PPO:
    batch_size: 218 
    buffer_size: 21800

Shooter3PPO:
    batch_size: 1024 
    buffer_size: 10240
  
Shooter4PPO:
    batch_size: 1024 
    buffer_size: 21800

Shooter5PPO:
    batch_size: 5120 
    buffer_size: 51200
    
Shooter6PPO:
    batch_size: 32 
    buffer_size: 2048
