default:
    trainer: ppo
    batch_size: 1024 
    buffer_size: 10240
    hidden_units: 128
    learning_rate_schedule: linear
    max_steps: 1.0e5
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: true
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
    lambd: 0.95

    epsilon: 0.2
    learning_rate: 3.0e-4
    beta: 5.0e-3

Shooter1PPO: 
    batch_size: 1024 
    buffer_size: 10240

Shooter2PPO: 
    batch_size: 1280 
    buffer_size: 10240

Shooter3PPO: 
    batch_size: 768 
    buffer_size: 10240
  
Shooter4PPO: 
    batch_size: 1024 
    buffer_size: 14336

Shooter5PPO:
    batch_size: 1024 
    buffer_size: 7680
    
Shooter6PPO: 
    batch_size: 1280 
    buffer_size: 14336
